### ISSUE TITLE
Introduce Vagrant resources for WSO2 Identity Server

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/vagrant-is#2]
**Description:**
It is required to introduce Vagrant resources (respective boxes and Vagrantfiles) for WSO2 Identity Server and Identity Server Analytics. Further, it was required to setup WSO2 Identity Server in single non-clustered, non-load balanced form with analytics support.

**Suggested Labels:**
New Feature

**Suggested Assignees:**
chirangaalwis

**Comment by DilanUA** [comment]
Closing since the initial task has been already completed.
